# Generated by Django 4.2.7 on 2023-11-12 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public_date_time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
