<<<<<<< HEAD
# Generated by Django 4.2.7 on 2023-11-12 16:48
=======
# Generated by Django 4.2 on 2023-11-14 20:43
>>>>>>> 42a0e17658b98c4b6411c16a4b015939e8acfdec

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='public_date_time',
<<<<<<< HEAD
            field=models.DateTimeField(auto_now=True),
=======
            field=models.DateTimeField(auto_now_add=True),
>>>>>>> 42a0e17658b98c4b6411c16a4b015939e8acfdec
        ),
    ]
